import { type AppType } from "next/dist/shared/lib/utils";
import "~/styles/globals.css";
import {Montserrat} from 'next/font/google'
import Head from "next/head";
import Navbar from "~/component/navbar";
import Footer from "~/component/Footer";

const monserat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont"
})

const MyApp: AppType = ({ Component, pageProps }) => {
    return (
        <>
        <Head>
            <title>Create T3 App</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar/>
        <main className={`${monserat.className} font-mont bg-light w-full min-h-screen`}>
            <Component {...pageProps} />
        </main>
        <Footer/>
        </>
    )
};

export default MyApp;
